name: "Pull Request Labeler"
on:
- pull_request_target

permissions: {}

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@f1a63e87db0c6baf19c5713083f8d00d789ca184 #v5
